version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./logs/:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: code/Dockerfile
    networks:
      - internal
networks:
  internal:
    driver: bridge