FROM php:8.2-fpm 

COPY ./code /var/www/html 

# you can install extensions here

# RUN apt-get update -y && apt-get install -y sendmail libpng-dev

# RUN apt-get update && \
#     apt-get install -y \
#         zlib1g-dev 

# RUN docker-php-ext-install gd

EXPOSE 9000